"""Password secure and email migration

Revision ID: dae1b8cb6748
Revises: 659ba078f387
Create Date: 2022-05-15 09:07:42.198503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dae1b8cb6748'
down_revision = '659ba078f387'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('secure_password', sa.String(length=255), nullable=False))
    op.create_unique_constraint(None, 'users', ['email'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'secure_password')
    op.drop_column('users', 'email')
    # ### end Alembic commands ###
